export const getData = [{
    Student_ID: 1,
    Mistake_Type: "Grammar",
    Original_Sentence: "I goes to school",
    Corrected_Sentence: "I go to school",
},
{
    Student_ID: 1,
    Mistake_Type: "Vocabulary",
    Original_Sentence: "She took the wrong bus",
    Corrected_Sentence: "She missed the bus",
},
{
    Student_ID: 1,
    Mistake_Type: "Grammar",
    Original_Sentence: "They is my friends",
    Corrected_Sentence: "They are my friends",
},
{
    Student_ID: 2,
    Mistake_Type: "Vocabulary",
    Original_Sentence: "He miss the bus",
    Corrected_Sentence: "He missed the bus",
},
{
    Student_ID: 2,
    Mistake_Type: "Grammar",
    Original_Sentence: "She were late",
    Corrected_Sentence: "She was late",
},
{
    Student_ID: 2,
    Mistake_Type: "Grammar",
    Original_Sentence: "They doesn't know",
    Corrected_Sentence: "They don't know",
},
{
    Student_ID: 3,
    Mistake_Type: "Vocabulary",
    Original_Sentence: "He don't have any",
    Corrected_Sentence: "He doesn't have any",
},
{
    Student_ID: 3,
    Mistake_Type: "Grammar",
    Original_Sentence: "She are happy",
    Corrected_Sentence: "She is happy",
},
{
    Student_ID: 3,
    Mistake_Type: "Vocabulary",
    Original_Sentence: "We doesn't like it",
    Corrected_Sentence: "We don't like it",
},
{
    Student_ID: 4,
    Mistake_Type: "Grammar",
    Original_Sentence: "He has car",
    Corrected_Sentence: "He has a car",
},
{
    Student_ID: 4,
    Mistake_Type: "Grammar",
    Original_Sentence: "They has a house",
    Corrected_Sentence: "They have a house",
},
{
    Student_ID: 4,
    Mistake_Type: "Vocabulary",
    Original_Sentence: "He bringed the book",
    Corrected_Sentence: "He brought the book",
},
{
    Student_ID: 5,
    Mistake_Type: "Vocabulary",
    Original_Sentence: "I taked the bus",
    Corrected_Sentence: "I took the bus",
},
{
    Student_ID: 5,
    Mistake_Type: "Grammar",
    Original_Sentence: "She have been there",
    Corrected_Sentence: "She has been there",
},
{
    Student_ID: 5,
    Mistake_Type: "Grammar",
    Original_Sentence: "They was there",
    Corrected_Sentence: "They were there",
},
{
    Student_ID: 1,
    Mistake_Type: "Vocabulary",
    Original_Sentence: "She learn fast",
    Corrected_Sentence: "She learns fast",
},
{
    Student_ID: 1,
    Mistake_Type: "Grammar",
    Original_Sentence: "We was playing",
    Corrected_Sentence: "We were playing",
},
{
    Student_ID: 2,
    Mistake_Type: "Grammar",
    Original_Sentence: "He bring a gift",
    Corrected_Sentence: "He brought a gift",
},
{
    Student_ID: 2,
    Mistake_Type: "Vocabulary",
    Original_Sentence: "She taked the wrong train",
    Corrected_Sentence: "She took the wrong train",
},
{
    Student_ID: 3,
    Mistake_Type: "Grammar",
    Original_Sentence: "He don't like it",
    Corrected_Sentence: "He doesn't like it",
},
{
    Student_ID: 3,
    Mistake_Type: "Vocabulary",
    Original_Sentence: "She went to the sea",
    Corrected_Sentence: "She went to the beach",
},
{
    Student_ID: 4,
    Mistake_Type: "Grammar",
    Original_Sentence: "They isn't coming",
    Corrected_Sentence: "They aren't coming",
},
{
    Student_ID: 4,
    Mistake_Type: "Vocabulary",
    Original_Sentence: "He eat the apple",
    Corrected_Sentence: "He ate the apple",
},
{
    Student_ID: 5,
    Mistake_Type: "Grammar",
    Original_Sentence: "She haven't seen him",
    Corrected_Sentence: "She hasn't seen him",
},
{
    Student_ID: 5,
    Mistake_Type: "Vocabulary",
    Original_Sentence: "They gone to the party",
    Corrected_Sentence: "They went to the party",
},
];

